### ISSUE TITLE
Error in searching torrents

### ISSUE THREAD

**Issue by TheRamann** [JimmyLaurent/torrent-search-api#131]
## Error

The npm module was working perfectly until a week ago when I started getting an error <br>
```cmd
TypeError: response.body.map is not a function
    at ThePirateBay.search (D:\Desktop\NodeJS\Easy-Torrent\node_modules\torrent-search-api\lib\providers\thepiratebay.js:48:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
```

## Expected solution

I suspect that the error is created from <a href="https://github.com/JimmyLaurent/torrent-search-api/blob/872e14d7acf801d7441d2d1a9576e7987664e50e/lib/providers/thepiratebay.js#L48">here</a> https://github.com/JimmyLaurent/torrent-search-api/blob/872e14d7acf801d7441d2d1a9576e7987664e50e/lib/providers/thepiratebay.js#L48

## Steps to reproduce the error
The error is produced in <a href="https://github.com/TheRamann/Easy-Torrent/blob/main/index.js"> here </a>
https://github.com/TheRamann/Easy-Torrent/blob/main/index.js

## Device Used
- Windows 10
- Node v14.15.4
- Npm v6.14.10

**Comment by damain** [comment]
+1 I also see this error

**Comment by damain** [comment]
> +1 I also see this error

I ran `npm update` and the error went away
