### ISSUE TITLE
Updating to 1.1.0 gives errors

### ISSUE THREAD

**Issue by YouriT** [JimmyLaurent/torrent-search-api#32]
After updating the module from `1.0.26` to latest `1.1.0`. The following very specific error arises for whatever search is made.

Call: `search(...)`
Arguments: 
```
[ 'torrent9',
  '1337x',
  'ThePirateBay',
  'Yggtorrent',
  'KickassTorrents',
  'Rarbg',
  'TorrentProject',
  'torrentz2' ] '1080' undefined undefined
```

Error thrown:
```
TypeError: fn.apply is not a function
    at .../node_modules/wrap-fn/index.js:75:16
    at .../node_modules/wrap-fn/index.js:57:27
    at get (.../node_modules/x-ray-scraper/src/crawler/index.js:75:27)
    at next (.../node_modules/enqueue/index.js:70:17)
    at .../node_modules/enqueue/index.js:48:12
    at crawler (.../node_modules/x-ray-scraper/src/crawler/index.js:52:7)
    at Promise (.../node_modules/x-ray-scraper/src/request.js:7:7)
    at new Promise (<anonymous>)
    at request (.../node_modules/x-ray-scraper/src/request.js:5:12)
    at getLoadedSource (.../node_modules/x-ray-scraper/src/source.js:8:12)
    at crawl (.../node_modules/x-ray-scraper/src/Xray.js:31:14)
    at Function.crawl.then (.../node_modules/x-ray-scraper/src/Xray.js:87:14)
```

I'm digging I will post my findings.

**Comment by JimmyLaurent** [comment]
Check the version of "x-ray-scraper" package in you node_modules dependencies, and update it to 3.0.3 if you are in 3.0.2.

**Comment by YouriT** [comment]
`x-ray-scraper` is at `3.0.3`

From what I see, in [torrent-provider](https://github.com/JimmyLaurent/torrent-search-api/blob/master/lib/torrent-provider.js#L311) you pass in the filters instead of passing a driver to `Xray`. `Xraj.js` L11 states: `function Xray(driver) {` which specifies it should be the driver. Meaning that you pass an object to the `Crawler` "constructor" instead of the driver, leading to the fn.apply error.

**Comment by JimmyLaurent** [comment]
It's updated, thanks.

**Comment by YouriT** [comment]
Great :)
