### ISSUE TITLE
RARBG error

### ISSUE THREAD

**Issue by moesalih** [JimmyLaurent/torrent-search-api#4]
I'm getting the following error occasionally:
```
TypeError: Cannot read property 'then' of undefined
    at Rarbg.search (/app/node_modules/torrent-search-api/lib/providers/rarbg.js:31:7)
    at Promise.all.selectedProviders.map.p (/app/node_modules/torrent-search-api/index.js:55:53)
    at Array.map (native)
    at TorrentSearchApi._search (/app/node_modules/torrent-search-api/index.js:55:42)
    at TorrentSearchApi.search (/app/node_modules/torrent-search-api/index.js:34:19)
```
Any thoughts?

**Comment by JimmyLaurent** [comment]
It was a simple mistake in the "_ensureLogin" method of rarbg provider.
Check the last release 1.0.14, it should be better.

**Comment by moesalih** [comment]
Thanks for the quick fix.
