### ISSUE TITLE
Upgrade cloudscraper to solve Challenge evaluation failed due to unexpected token

### ISSUE THREAD

**Issue by qymspace1** [JimmyLaurent/torrent-search-api#68]
I have this error reporting from cloudscraper
```Unhandled rejection ParserError:
2019-05-23T16:03:05.395672+00:00 app[worker.1]: ### Cloudflare may have changed their technique, or there may be a bug.
2019-05-23T16:03:05.395673+00:00 app[worker.1]: ### Bug Reports: https://github.com/codemanki/cloudscraper/issues
2019-05-23T16:03:05.395675+00:00 app[worker.1]: ### Check the detailed exception message that follows for the cause.
2019-05-23T16:03:05.395677+00:00 app[worker.1]:
2019-05-23T16:03:05.395679+00:00 app[worker.1]: SyntaxError: Challenge evaluation failed: Unexpected token |
2019-05-23T16:03:05.395680+00:00 app[worker.1]: at solveChallenge (/app/node_modules/cloudscraper/index.js:254:21)
2019-05-23T16:03:05.395681+00:00 app[worker.1]: at Timeout._onTimeout (/app/node_modules/cloudscraper/index.js:179:7)
2019-05-23T16:03:05.395683+00:00 app[worker.1]: at ontimeout (timers.js:436:11)
2019-05-23T16:03:05.395684+00:00 app[worker.1]: at tryOnTimeout (timers.js:300:5)
2019-05-23T16:03:05.395686+00:00 app[worker.1]: at listOnTimeout (timers.js:263:5)
2019-05-23T16:03:05.395687+00:00 app[worker.1]: at Timer.processTimers (timers.js:223:10)```

**Possible solutions:** Upgrade cloudscraper to the latest version fixes the error. Got that from [cloudscraper](https://github.com/codemanki/cloudscraper/issues/190) and tested it on my instance.

**Comment by JimmyLaurent** [comment]
Cloudscraper has been upgraded in the last release (2.1.0).
